[build]
  command = "./build.sh"
  functions = "functions"
  publish = "public"

[build.environment]
  GO_IMPORT_PATH = "github.com/ertush/users-go-api"
  GO111MODULE = "on"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200 